export function describeInternalRoute(path: string) {
  const normalized = path.trim() || '/'

  if (normalized === '/' || normalized.startsWith('/dashboard')) return '대시보드'
  if (normalized === '/content') return '발행 큐'
  if (normalized.startsWith('/content/automation')) return '자동화 큐'
  if (normalized.startsWith('/content/distribution')) return '배포 관리'
  if (normalized.startsWith('/content/templates')) return '템플릿'
  if (normalized.startsWith('/content/')) return '콘텐츠 상세'
  if (normalized.startsWith('/showroom')) return '쇼룸'
  if (normalized.startsWith('/image-assets/upload')) return '이미지 자산 업로드'
  if (normalized.startsWith('/image-assets')) return '이미지 자산 관리'
  if (normalized.startsWith('/consultation')) return '상담 관리'
  if (normalized.startsWith('/measurement/upload')) return '실측 업로드'
  if (normalized.startsWith('/measurement')) return '실측 보관함'
  if (normalized.startsWith('/homepage-concept')) return '홈페이지 컨셉'
  if (normalized.startsWith('/admin/migration')) return '마이그레이션 관리'
  if (normalized.startsWith('/admin/archive')) return '아카이브 관리'
  if (normalized.startsWith('/admin/test-console')) return '테스트 콘솔'
  if (normalized.startsWith('/login')) return '로그인'
  return '내부 운영 화면'
}
